services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=library
      - POSTGRES_USER=omadbeksalomov
      - POSTGRES_PASSWORD=2403
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=omadbeksalomov
      - POSTGRES_PASSWORD=2403
    depends_on:
      - db
